/**
 * Player-facing strings, keyed not concatenated (ADR-020). English-only at launch; adding a
 * locale later means populating a sibling module, not refactoring call sites. Latin terms
 * (Opera, Suasio, Katabasis, …) stay untranslated regardless of locale — they are the voice.
 * This grows as the UI lands (step 4); it starts with the few labels the skeleton needs.
 */
export const strings = {
  appName: 'Panvitium',
  menu: {
    tagline: 'Per vitia, ad solium.',
    continue: 'Continue',
    newGame: 'New Game',
    newGamePrompt:
      'Abandon this descent and begin anew? Your current lifetime and all progress will be lost.',
    newGameConfirm: 'Begin anew',
    cancel: 'Keep descending',
    settings: 'Settings',
    about: 'About',
    back: 'Back',
    aboutBody:
      'Panvitium is an idle descent into damnation. Corrupt the living into reprobates, cull them for their souls, and spend those souls climbing the hierarchy of Hell — lifetime after lifetime, world without end.\n\nThe Latin is left untranslated, as it should be. Everything else, you will learn by doing.',
  },
  resources: {
    souls: 'Souls',
    gold: 'Gold',
    influence: 'Influence',
  },
  rooms: {
    studio: 'Studio',
    altar: 'Altar',
    invocation: 'Invocation Room',
  },
  reprobates: 'Reprobates',
  opera: {
    suasio: 'Suasio',
    decimatio: 'Decimatio',
    depraedatio: 'Depraedatio',
    indagatio: 'Indagatio',
    emptio: 'Emptio',
    suggestion: 'Suggestion',
    logismoi: 'Logismoi',
    imperium: 'Imperium',
    caedis: 'Caedis',
    pogrom: 'Pogrom',
    purgatio: 'Purgatio',
    tempt: 'Tempt',
    cull: 'Cull',
    purge: 'Purge',
    pogromEmpty: 'No reprobates to purge',
    logs: 'Logs',
    back: 'Back',
    selectLedger: 'select a ledger',
    underway: 'A rite is already underway.',
    emptyLog: 'The terminal log is empty. Nothing has been done.',
    suasioIntro: 'The temptations, written to be spoken. Whisper one and wait.',
    notYet: 'not yet inscribed',
    idle: 'No rite underway.',
    search: 'Search',
    buy: 'Buy',
    indagatioIntro:
      'A long, patient search of the world\u2019s corners. Most of what is found cannot be picked up — only listed for purchase.',
    emptioIntro: 'What the search surfaced, ready to be bought. The deal itself can still sour.',
    emptioEmpty: 'The market shows nothing. Indagatio surfaces what can be bought.',
    indagatioCta: 'Begin the search',
    depraedatioIntro:
      'Eight trades, one to each Sin. A trade is deepened for gold; as its roots spread, its reach among the reprobates grows \u2014 and so does its take.',
    sinLocked: 'Locked',
  },
  /**
   * The Mercatus system (Vitium Mercatura rework): eight trades, exactly one per Cardinal Sin.
   * Display names are the Latin *Mercatus <genitive>* forms, untranslated (ADR-020). Copy stays
   * in the established register \u2014 a trade has roots and reach, it is deepened, cut back,
   * sold off.
   */
  mercatus: {
    names: {
      gula: 'Mercatus Gulae',
      luxuria: 'Mercatus Luxuriae',
      avaritia: 'Mercatus Avaritiae',
      tristitia: 'Mercatus Tristitiae',
      ira: 'Mercatus Irae',
      acedia: 'Mercatus Acediae',
      vanagloria: 'Mercatus Vanagloriae',
      superbia: 'Mercatus Superbiae',
    } as Record<string, string>,
    /** The depth meter label: "roots 12 / 20". */
    roots: 'roots',
    /** The revenue/s readout suffix: "4.2 gold/s". */
    perSecond: '/s',
    deepen: 'Deepen',
    cutBack: 'Cut back',
    sellOff: 'Sell off',
    /** Locked rows: the trade opens at its Sin's first level. */
    lockedHint: 'opens at Level 1',
    /** Depth-capped rows: deepening resumes at the next Sin level. */
    capped: 'its roots can reach no deeper at this rank',
    /**
     * Per-trade signature clauses (§1.5, amended) — shown as the row name's tooltip. In-register:
     * roots, reach, take; never analytics vocabulary.
     */
    clauses: {
      gula: 'Its patrons spend a quarter more.',
      luxuria: 'Its corruption breeds a quarter richer.',
      avaritia: 'Each depth bargains the next a sliver cheaper.',
      tristitia: 'Every depth thickens the despair it feeds.',
      ira: 'Every depth sharpens the knives it sells.',
      acedia: 'Its take never sleeps, and its torpor stretches the hours away.',
      vanagloria: 'Deep roots pay tribute \u2014 a share of your utmost influence, each second.',
      superbia: 'Costlier to deepen; its take and its breeding run a third richer.',
    } as Record<string, string>,
    /** The Foedus tier badge prefix; tier rendered as a Roman numeral (Foedus II). */
    foedus: 'Foedus',
    foedusTitle:
      'Bound in Foedus with an active ceremony \u2014 its take grows, the rite costs less.',
  },
  acolytes: {
    acolyte: 'Acolyte',
    assign: 'Assign one more',
    unassign: 'Recall one',
    delegationLabel: 'Delegated acolytes',
    idle: 'idle',
  },
  compositum: {
    heading: 'Vitium Compositum',
    start: 'Begin',
    stop: 'End',
    noCost: 'no upkeep',
    cost: 'Cost',
    outcomes: 'Expected outcomes',
    noOutcome: '\u2014',
    rising: 'and rising',
    converts: 'converts',
    only: 'only',
    breeds: 'breeds reprobates at',
    of: 'of',
    slowsBirths: 'slows reprobate births by',
    raisesSuicide: 'raises base suicide rate by',
    raisesMurder: 'raises base murder rate by',
    culls: 'culls',
    ofAll: 'of all reprobates/s',
    deepens: 'deepens',
    penaltiesBy: 'penalties by',
    offlineGain: 'offline gain rate',
    panvitiumEffect: 'harvests souls and breeds reprobates, ramping each second',
    names: {
      bacchanal: 'Bacchanal',
      'loan-shark-op': 'Loan Shark Op',
      charity: 'Charity Drive',
      gala: 'Gala',
      'outrage-cycle': 'Outrage Cycle',
      'no-babies-movement': 'No-babies Movement',
      'doom-gathering': 'Doom Gathering',
      'ethnocentric-revolt': 'Ethnocentric Revolt',
      'enraging-broadcast': 'Enraging Broadcast',
      'dolce-far-niente': 'Dolce Far Niente',
      vegas: 'Vegas',
      crusade: 'Crusade',
      panvitium: 'Panvitium',
    } as Record<string, string>,
    panvitiumGate: 'Requires every Sin at Level 3.',
    panvitiumReady: 'The streets are ready to burn. 10000 gold/s, 100 influence/s — and rising.',
    panvitiumActive: 'The Sins have taken the streets.',
    panvitiumBurning: 'Burning\u2026',
    panvitiumBegin: 'Unleash',
    panvitiumConfirm: 'Yes \u2014 let it all burn',
    panvitiumCancel: 'Not yet',
  },
  invocations: {
    intro: 'Names called up from below. Each asks a price in souls and stays until dispelled.',
    empty:
      'The seals lie unlit. Gather invoking power \u2014 from maleficia \u2014 to glimpse what waits beneath the ink.',
    power: 'Invoking power',
    summon: 'Summon',
    dispel: 'Dispel',
    active: 'bound',
    free: 'no soul cost',
    names: {
      familiar: 'Familiar',
      imp: 'Imp',
      upir: 'Upir',
      fama: 'Fama',
      nightmare: 'Nightmare',
      harpy: 'Harpy',
      lamia: 'Lamia',
      lemure: 'Lemure',
      behemoth: 'Behemoth',
      midas: 'Midas',
      plutus: 'Plutus',
      succubus: 'Succubus',
      doppelgaenger: 'Doppelg\u00e4nger',
      astiwihad: 'Astiwihad',
      aurevora: 'Aurevora',
      erinyes: 'Erinyes',
      morpheus: 'Morpheus',
      specunitas: 'Specunitas',
    } as Record<string, string>,
    // Analytics → Invocations tab.
    noneBound: 'No invocations are bound.',
    every: 'every',
    /** Outcome unit nouns for a runner's expected per-cycle yield (mean ± sd). */
    outcomeUnits: {
      soul: 'soul',
      souls: 'souls',
      reprobate: 'reprobate',
      reprobates: 'reprobates',
      gold: 'gold',
      maleficium: 'maleficium',
      maleficia: 'maleficia',
    },
    /** Noun labels for the live quantified "total effect" of passive invocations (composed with the
     *  +X% / ×N value the Analytics tab computes from the current modifier bundle). */
    effectLabels: {
      influence: 'influence gain',
      decimatioEff: 'Decimatio efficiency',
      vmOutput: 'Vitium Mercatura output',
      stellar: 'Stellar chance',
      offline: 'offline gain',
      baseSuicide: 'base suicide rate',
      gold: 'gold',
      apocalyptic: 'Apocalyptic chance',
      apocLocked: 'Apocalyptic locked to zero',
      suasioEff: 'Suasio efficiency',
      playerEff: 'player efficiency',
    },
    /** Qualitative fallback line for invocations whose effect isn't a live modifier-bundle magnitude
     *  (Katabasis / per-tick apex / conversion-bias entities). Runners show action + outcome + cycle
     *  time instead; the other passives show the computed quantified effect. */
    effects: {
      familiar: '+33% player efficiency, plus a background Indagatio.',
      imp: 'A background Good-only Decimatio — culls reprobates.',
      upir: 'A background Good-only Decimatio — culls reprobates.',
      lamia: 'A background Suasio, and shifts Suasio toward success.',
      fama: 'Raises influence gain.',
      nightmare: 'Raises the base reprobate suicide rate.',
      harpy: 'Raises Decimatio efficiency.',
      lemure: 'Raises the offline gain rate.',
      behemoth: 'Raises the Stellar success chance.',
      midas: '×3 gold gain — but ×100 the Apocalyptic chance.',
      plutus: 'Raises Vitium Mercatura output.',
      succubus: 'Raises Suasio efficiency, at a cut to gold.',
      doppelgaenger: '+50% player efficiency, at half influence gain.',
      astiwihad: 'Each second, a chance to wipe all reprobates into souls.',
      aurevora: 'Player efficiency ramps exponentially — burns gold, self-dispels at zero.',
      erinyes: 'At the next Katabasis: kills every reprobate and permanently doubles efficiency.',
      morpheus: 'Holds the world still; at Katabasis, maxes the carry-over rolls.',
      specunitas: 'Apex Vanagloria invocation.',
    } as Record<string, string>,
  },
  maleficia: {
    intro:
      'What has been found, paid for, and brought home. Each item has its own price in attention.',
    empty: 'Empty hooks and clean dust-rings. Nothing has yet been found or purchased.',
    rarity: {
      common: 'common',
      rare: 'rare',
      profane: 'profane',
      anathema: 'anathema',
    },
    invokingPower: 'invoking power',
    use: 'Use',
    handOfGloryLeft: 'of fevered generation remain',
    defixioOn: 'A curse gnaws at the reprobates',
    oracleCaption: 'What the omens already weigh — the odds of each outcome, should you act now:',
  },
  analytics: {
    title: 'Analytics',
    main: 'Main',
    resources: 'Resources',
    reprobates: 'Reprobates',
    acolytes: 'Acolytes',
    invocations: 'Invocations',
    generation: 'Generation',
    deaths: 'Deaths',
    noAcolytes: 'No acolytes recruited yet.',
    ofMax: 'of',
    playerEfficiency: 'Player action efficiency',
  },
  emails: {
    title: 'Emails',
    inboxEmpty: 'No correspondence yet. The world has not noticed you.',
    unread: 'unread',
    from: 'From',
    back: 'Back to inbox',
    markAllRead: 'Mark all read',
    // Provisional content (Phase 5.2) — sender / subject / body keyed by the sim email id.
    catalog: {
      welcome: {
        from: 'The Management',
        subject: 'Welcome to the work',
        body: 'Your terminal is provisioned. You will receive correspondence here as the world begins to feel your attentions. Most of it will be complaints. Read them, or do not — the rot proceeds either way.',
      },
      'first-reprobates': {
        from: 'The Vesper Tribune',
        subject: 'A curious malaise in the quarter',
        body: 'Residents report a creeping listlessness, a taste for small ruin. Our correspondents can find no cause. We are sure it is nothing. We are sure of very little lately.',
      },
      'first-business': {
        from: 'A former customer',
        subject: 'I want to speak to someone',
        body: 'I bought what you were selling and I am not myself since. My wife says my eyes have gone flat. Who do I write to about this? Is anyone reading these?',
      },
      'newsletter-influence': {
        from: 'The Vesper Tribune',
        subject: 'On the new patron everyone is whispering about',
        body: 'A quiet hand is said to move beneath the city\u2019s affairs — generous, they say, and never seen. We would request an interview, but our editor has developed a sudden and total disinterest in the story.',
      },
      'class-action': {
        from: 'Holloway & Crane, Attorneys',
        subject: 'NOTICE OF PENDING ACTION',
        body: 'You are named in a class action brought by some four hundred claimants alleging harm arising from your enterprises. Please retain all records. Settlement may be possible; restitution, we suspect, is not.',
      },
    },
  },
  welcomeBack: {
    title: 'While you were away',
    away: 'Away for',
    nothing: 'The lair lay quiet; nothing stirred.',
    dismiss: 'Resume',
  },
  settings: {
    title: 'Settings',
    exportTitle: 'Export save',
    exportHint: 'Copy this text somewhere safe to back up your game or move it to another device.',
    export: 'Generate export',
    copy: 'Copy',
    copied: 'Copied',
    importTitle: 'Import save',
    importHint: 'Paste an exported save to replace your current game. This overwrites everything.',
    importPlaceholder: 'Paste your exported save here…',
    import: 'Import',
    importError: 'That does not look like a valid Panvitium save.',
    resetTitle: 'Hard reset',
    resetHint: 'Erase this game and begin again from nothing. There is no undo.',
    reset: 'Erase everything',
    resetConfirm: 'Erase everything?',
    resetYes: 'Yes, erase',
    cancel: 'Cancel',
    close: 'Close',
  },
  tiers: {
    stellar: 'Stellar',
    excellent: 'Excellent',
    good: 'Good',
    neutral: 'Neutral',
    bad: 'Bad',
    terrible: 'Terrible',
    apocalyptic: 'Apocalyptic',
  },
  sins: {
    // Each Prince also carries the lore surfaced in the Katabasis takeover: an epithet, the Sin's
    // skill name + its derived-multiplier effect, and the per-rank (level-up) effect (03 §1).
    gula: {
      prince: 'Beelzebub',
      latin: 'Gula',
      english: 'Gluttony',
      epithet: 'Lord of the Flies',
      skill: 'Insatiability',
      skillEffect: 'Decreases overall Terrible and Apocalyptic outcomes.',
      levelEffect: 'Each level raises your online action efficiency.',
    },
    luxuria: {
      prince: 'Asmodeus',
      latin: 'Luxuria',
      english: 'Lust',
      epithet: 'King of the Nine Hells',
      skill: 'Seduction',
      skillEffect: 'Increases overall reprobate generation rate.',
      levelEffect: 'Each level keeps more reprobates on descent.',
    },
    avaritia: {
      prince: 'Mammon',
      latin: 'Avaritia',
      english: 'Greed',
      epithet: 'The Hoarder Below',
      skill: 'Golden Hand',
      skillEffect: 'Increases overall gold gain rate.',
      levelEffect: 'Each level keeps more gold on descent.',
    },
    tristitia: {
      prince: 'Leviathan',
      latin: 'Tristitia',
      english: 'Sorrow',
      epithet: 'The Coiled Deep',
      skill: 'Resignation',
      skillEffect: 'Increases Suasio success and action efficiency.',
      levelEffect: 'Each level raises the base reprobate suicide chance.',
    },
    ira: {
      prince: 'Satan',
      latin: 'Ira',
      english: 'Wrath',
      epithet: 'The Adversary',
      skill: 'Retribution',
      skillEffect: 'Increases Decimatio success and action efficiency.',
      levelEffect: 'Each level raises acolyte and invocation efficiency.',
    },
    acedia: {
      prince: 'Belphegor',
      latin: 'Acedia',
      english: 'Sloth',
      epithet: 'The Idle Throne',
      skill: 'Procrastination',
      skillEffect: 'Increases offline generation, gold and efficiency.',
      levelEffect: 'Each level compounds your offline time.',
    },
    vanagloria: {
      prince: 'Rosier',
      latin: 'Vanagloria',
      english: 'Vainglory',
      epithet: 'The Fair Tongue',
      skill: 'Acclaim',
      skillEffect: 'Increases maximum influence.',
      levelEffect: 'Each level raises your influence gain rate.',
    },
    superbia: {
      prince: 'Lucifer',
      latin: 'Superbia',
      english: 'Pride',
      epithet: 'The Light-Bringer',
      skill: 'Morning Star',
      skillEffect: 'Increases overall Stellar outcomes.',
      levelEffect: 'Each level keeps more maleficia on descent.',
    },
  },
  altar: {
    intro:
      'The Devotion owed each Prince, and the rank it buys you. Bound sigils show here once they bite.',
    descend: 'Lay upon the altar — descend',
    descendArm: 'Once you descend there is no climbing back — tap again to commit',
    descendConfirm: 'Descend — no return',
    sigilsNone: 'No sigils bound.',
  },
  katabasis: {
    title: 'Katabasis',
    intro:
      'You lie still; the soul descends to settle its accounts. Hold to pour souls into a Prince or a seal — the longer you hold, the faster they flow. When you are ready, ascend.',
    pool: 'Souls in the pool',
    skill: 'Skill',
    mastered: 'Mastered',
    confirm: 'Ascend — rise to the world',
    pageSins: 'Cardinal Sins',
    pageSigils: 'The Goetia',
    prev: 'Back',
    next: 'Onward',
    holdOffer: 'Hold to offer',
    holdLock: 'Hold to bind',
    holdUnlock: 'Hold to unbind',
    recapTitle: 'You rise',
    soulsCarried: 'Souls carried',
    goldKept: 'Gold remaining',
    reprobatesKept: 'Reprobates still yours',
    maleficiaKept: 'Maleficia retained',
    maleficiaLost: 'Maleficia lost',
    rise: 'Rise',
  },
  sigils: {
    heading: 'The Goetia',
    intro:
      'Bind souls to a seal for a passive boon. Bindings persist through every descent \u2014 unbind a seal to reclaim its souls.',
    unbind: 'Unbind',
    unbindAll: 'Unbind all',
    lock: 'Bind',
    unlock: 'Unbind',
    names: {
      5: 'Marbas',
      6: 'Valefor',
      7: 'Aamon',
      11: 'Gusion',
      16: 'Zepar',
      18: 'Bathin',
      20: 'Purson',
      23: 'Aim',
      31: 'Foras',
      32: 'Semet',
      35: 'Marchosias',
      38: 'Halphas',
      40: 'Raum',
      49: 'Crocell',
      60: 'Vapula',
      71: 'Dantalion',
    } as Record<number, string>,
    descriptions: {
      5: 'Influence gain \u2191',
      6: 'Gold gain \u2191',
      7: 'Reprobate generation \u2191',
      11: 'Terrible chance \u2193',
      16: 'Reprobate generation \u2193',
      18: 'Acolyte efficiency \u2191',
      20: 'Gold kept on descent \u2191',
      23: 'Choleric murder rate \u2191',
      31: 'Apocalyptic chance \u2193',
      32: 'Gold, maleficia & reprobates kept on descent \u2191',
      35: 'Maximum influence \u2191',
      38: 'Maleficia kept on descent \u2191',
      40: 'Decimatio efficiency \u2191',
      49: 'Reprobate suicide rate \u2191',
      60: 'Vitium Mercatura output \u2191',
      71: 'Suasio efficiency \u2191',
    } as Record<number, string>,
  },
  achievements: {
    ledger: 'Achievements',
    intro: 'A tally of what you have done. Sealed entries reveal their name once earned.',
    hiddenName: 'Sealed',
    unlocked: 'Achievement unlocked',
    names: {
      first_stain: 'First Stain',
      first_harvest: 'First Harvest',
      first_descent: 'First Descent',
      first_bargain: 'First Bargain',
      council_convenes: 'The Council Convenes',
      profane_possession: 'Profane Possession',
      anathema: 'Anathema',
      court_of_spires: 'Court of Spires',
      single_minded: 'Single-Minded',
      eight_at_the_table: 'Eight at the Table',
      the_long_burn: 'The Long Burn',
      curator: 'Curator',
      crown_of_hell: 'The Crown of Hell',
      semet: 'Semet',
    } as Record<string, string>,
    descriptions: {
      first_stain: 'Generate your first reprobate.',
      first_harvest: 'Earn your first soul.',
      first_descent: 'Complete your first Katabasis.',
      first_bargain: 'Acquire your first maleficium.',
      council_convenes: 'Reach Level 1 in every Cardinal Sin.',
      profane_possession: 'Own a profane maleficium.',
      anathema: 'Own an anathema maleficium.',
      court_of_spires: 'Reach 10,000 maximum influence.',
      single_minded: 'Reach Level 4 in any one Cardinal Sin.',
      eight_at_the_table: 'Reach Level 3 in every Cardinal Sin.',
      the_long_burn: 'Sustain Panvitium for 60 seconds.',
      curator: 'Own every maleficium in the catalog.',
      crown_of_hell: 'Reach Level 4 in every Cardinal Sin.',
      semet: 'Reveal the Eternal Sin.',
    } as Record<string, string>,
  },
  eternal: {
    // The blacked-out ninth Sin, shown in the Katabasis menu once all eight are mastered.
    herald:
      'Something stands above the eight. It has no name you can read \u2014 yet it takes what you give.',
    unknown: '\u2588\u2588\u2588\u2588\u2588',
    ninth: 'The Ninth',
    complete: 'It knows your name. It was always yours.',
    // Revealed identity.
    name: 'Semet',
    epithet: 'The King of All Sins',
    // The reveal / credits screen.
    revealKicker: 'The name beneath the ink resolves.',
    gloss: 'Semet \u2014 "oneself." There was never another prince. There was only you.',
    verse:
      'Iam pridem scis te perditum esse. Quiescere non potes, sed nihil agis: nihil enim venenum acerbissimum est, ornamentum gravissimum, quod cervicem premit nec umquam deponi patitur. At inter has tenebras amor eorum iustus ignem accendit, eaque sola flamma, quamvis tenuis, viam tibi monstrat.',
    scoreLabel: 'Time to ascend',
    dismiss: 'Close the book',
  },
  sync: {
    title: 'Cloud Archive',
    intro: 'Bind this lifetime to a sigil bearing your name; the work follows you across devices.',
    signedInAs: 'Signed in as',
    signOut: 'Sign out',
    signInHint: 'A magic link will be sent to this address.',
    emailLabel: 'Email',
    sendLink: 'Send the link',
    syncNow: 'Sync now',
    syncing: 'Reaching the archive\u2026',
    syncedAt: 'Last synced',
    syncIdle: 'Not yet synced',
    syncError: 'Sync failed',
    dismissError: 'Dismiss',
    conflict: {
      title: 'Two histories diverge',
      intro:
        'The cloud holds a different lifetime than this device. Choose which to keep \u2014 the other will be overwritten.',
      thisDevice: 'This device',
      cloud: 'Cloud',
      souls: 'Souls',
      saveVersion: 'Save version',
      lastTickAt: 'Last play',
      keepLocal: 'Keep this device',
      keepServer: 'Use the cloud',
    },
  },
} as const;

export type Strings = typeof strings;
